
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// CUST_LOCATION
export const CREATE_CUST_LOCATION_SUCCESS = "CREATE_CUST_LOCATION_SUCCESS";
export const DELETE_CUST_LOCATION_SUCCESS = "DELETE_CUST_LOCATION_SUCCESS";
export const FINDBY_CUSTOMER_NAME_CUST_LOCATION_SUCCESS = "FINDBY_CUSTOMER_NAME_CUST_LOCATION_SUCCESS";
export const GET_CUST_LOCATION_SUCCESS = "GET_CUST_LOCATION_SUCCESS";
export const LIST_CUST_LOCATION_SUCCESS = "LIST_CUST_LOCATION_SUCCESS";
export const UPDATE_CUST_LOCATION_SUCCESS = "UPDATE_CUST_LOCATION_SUCCESS";

// CUSTOMER
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const LIST_CUSTOMER_SUCCESS = "LIST_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";

// DEVICE
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
export const FINDBY_CUSTOMER_DEVICE_SUCCESS = "FINDBY_CUSTOMER_DEVICE_SUCCESS";
export const FINDBY_CUSTOMER_LOCATION_DEVICE_SUCCESS = "FINDBY_CUSTOMER_LOCATION_DEVICE_SUCCESS";
export const GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";
export const LIST_DEVICE_SUCCESS = "LIST_DEVICE_SUCCESS";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
